---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: security
spec:
  storageClassName: app-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
