---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: security
  labels:
    app: postgres
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: backend
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      securityContext: 
        runAsNonRoot: true
        runAsUser:  999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: db-postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: c-db-port
          envFrom:
            - configMapRef:
                name: app-cm
          env:
            ### Not for production just connect/password troubleshooting
            # - name: POSTGRES_HOST_AUTH_METHOD
            #   value: "trust"  # ﺪﻫ ﻪﻴﺨﻠﻳ ﺎﻟﺩﺎﺗﺍ ﺐﻳﺯ ﺖﻘﺒﻟ ﺄﻳ ﺡﺩ ﻢﻧ ﺝﻮﻫ ﺎﻠﻛﻼﺴﺗﺭ (ﻞﻠﺗﺄﻛﺩ ﻒﻘﻃ)
            # - name: POSTGRES_USER
            # - name: POSTGRES_USER
            ### if there is a diff between image, api or any image connect with
            # - name: POSTGRES_INITDB_ARGS
            #   value: "--auth-host=md5 --auth-local=md5"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: db-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD 
                  name: db-secrets
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: pgdata
              name: postgres-db
            
      volumes:
        - name: postgres-db
          persistentVolumeClaim:
            claimName: db-pvc
