---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-db-networkpolicy
  namespace: security
spec:
  podSelector:
    matchLabels:
      app: redis
      tier: backend
  policyTypes:
    - Ingress
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: worker
            tier: backend
      - podSelector:
          matchLabels:
            app: vote
            tier: frontend
    ports:
      - protocol: TCP
        port: c-redis-port   
